### ISSUE TITLE
能加分页查询吗

### ISSUE THREAD

**Issue by ounione** [Fidetro/FFDB#4]

**Comment by ounione** [comment]
> ```
>     Select
>     .begin(@"*")
>     .from([ClassRoom class])
>     .limit(@"?")
>     .offset(@"?")
>     .endQuery(@[@(5),@(5)],[ClassRoom class],nil,^(NSArray *result){
>         NSLog(@"%@",result);
>     });
> ```
> 
> 这样应该能先临时解决你的问题？后续会加上

我先试试，感谢万分

**Comment by ounione** [comment]
> ```
>     Select
>     .begin(@"*")
>     .from([ClassRoom class])
>     .limit(@"?")
>     .offset(@"?")
>     .endQuery(@[@(5),@(5)],[ClassRoom class],nil,^(NSArray *result){
>         NSLog(@"%@",result);
>     });
> ```
> 
> 这样应该能先临时解决你的问题？后续会加上
大佬你好，我看你写了不少功能但没有注释，比较难懂。可以问下方便给联系方式么，有几个问题想咨询

**Comment by ounione** [comment]
> ```
>     Select
>     .begin(@"*")
>     .from([ClassRoom class])
>     .limit(@"?")
>     .offset(@"?")
>     .endQuery(@[@(5),@(5)],[ClassRoom class],nil,^(NSArray *result){
>         NSLog(@"%@",result);
>     });
> ```
> 
> 这样应该能先临时解决你的问题？后续会加上



> ```
>     Select
>     .begin(@"*")
>     .from([ClassRoom class])
>     .limit(@"?")
>     .offset(@"?")
>     .endQuery(@[@(5),@(5)],[ClassRoom class],nil,^(NSArray *result){
>         NSLog(@"%@",result);
>     });
> ```
> 
> 这样应该能先临时解决你的问题？后续会加上

大佬你好，我看你写了不少功能但没有注释，比较难懂。可以问下方便给联系方式么，有几个问题想咨询

**Comment by Fidetro** [comment]
这里问吧

**Comment by ounione** [comment]
> 这里问吧

app想模拟网页，需要一个分页查询功能，比如页面可以上拉加载更多数据，数据为倒序返回（按创建时间最新或者按主键id倒序）。这个limit和offset能看懂，endQuery第一个参数数组怎么理解，按主键id倒序该怎么写

**Comment by Fidetro** [comment]
倒序可以用orderby，
```objc
    Select
    .begin(@"*")
    .from([ClassRoom class])
    .orderBy(@"primaryKeyColumn DESC")
    .limit(@"?")
    .offset(@"?")
    .endQuery(@[@(5),@(10)],[ClassRoom class],nil,^(NSArray *result){
        NSLog(@"%@",result);
    });
```
不过我发现这里之前写错了，少了个空格，晚些我处理下这个问题
https://github.com/Fidetro/FFDB/blob/022062466846d46e68c967f1c60a13c9482faba1/FFDB/OrderBy.m#L18C4-L18C4
```objc
// 错误
self.stmt = [NSString stringWithFormat:@"%@orderby %@ ",stmt,format];
// 预期
self.stmt = [NSString stringWithFormat:@"%@order by %@ ",stmt,format];
```
endQuery的参数是fmdb的用法，可以看下[这里](https://github.com/ccgus/fmdb#data-sanitization)，5代表limit 5，10代表offset10，当然你也可以不这么用，这样写也可以

```objc
    Select
    .begin(@"*")
    .from([ClassRoom class])
    .orderBy(@"primaryKeyColumn DESC")
    .limit(@"5")
    .offset(@"10")
    .endQuery(nil,[ClassRoom class],nil,^(NSArray *result){
        NSLog(@"%@",result);
    });
```

**Comment by ounione** [comment]
> https://github.com/Fidetro/FFDB/blob/022062466846d46e68c967f1c60a13c9482faba1/FFDB/OrderBy.m#L18C4-L18C4



> 倒序可以用orderby，
> 
> ```objc
>     Select
>     .begin(@"*")
>     .from([ClassRoom class])
>     .orderBy(@"primaryKeyColumn DESC")
>     .limit(@"?")
>     .offset(@"?")
>     .endQuery(@[@(5),@(10)],[ClassRoom class],nil,^(NSArray *result){
>         NSLog(@"%@",result);
>     });
> ```
> 
> 不过我发现这里之前写错了，少了个空格，晚些我处理下这个问题 https://github.com/Fidetro/FFDB/blob/022062466846d46e68c967f1c60a13c9482faba1/FFDB/OrderBy.m#L18C4-L18C4
> 
> ```objc
> // 错误
> self.stmt = [NSString stringWithFormat:@"%@orderby %@ ",stmt,format];
> // 预期
> self.stmt = [NSString stringWithFormat:@"%@order by %@ ",stmt,format];
> ```
> 
> endQuery的参数是fmdb的用法，可以看下[这里](https://github.com/ccgus/fmdb#data-sanitization)，5代表limit 5，10代表offset10，当然你也可以不这么用，这样写也可以
> 
> ```objc
>     Select
>     .begin(@"*")
>     .from([ClassRoom class])
>     .orderBy(@"primaryKeyColumn DESC")
>     .limit(@"5")
>     .offset(@"10")
>     .endQuery(nil,[ClassRoom class],nil,^(NSArray *result){
>         NSLog(@"%@",result);
>     });
> ```

理解了，试了下有用，感谢

**Comment by Fidetro** [comment]
Fixed [4.1.5](https://github.com/Fidetro/FFDB/releases/tag/4.1.5)
